### ISSUE TITLE
django.db.utils.DatabaseError: missing dimension value 

### ISSUE THREAD

**Issue by eykd** [ecometrica/django-dbarray#2]
I just recently started getting this error when running South migrations on a model using dbarray. Any idea what's behind this?

I'm currently tracking Django 1.4 alpha for this project, but I've seen this error in 1.3 as well.

Not sure if it will be helpful, but here's a traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_manager(settings)
  File "[...]/django/django/core/management/__init__.py", line 435, in execute_manager
    utility.execute()
  File "[...]/django/django/core/management/__init__.py", line 358, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "[...]/django/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "[...]/django/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "[...]/django/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "[...]/south/management/commands/syncdb.py", line 99, in handle_noargs
    management.call_command('migrate', **options)
  File "[...]/django/django/core/management/__init__.py", line 145, in call_command
    return klass.execute(*args, **defaults)
  File "[...]/django/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "[...]/south/management/commands/migrate.py", line 105, in handle
    ignore_ghosts = ignore_ghosts,
  File "[...]/south/migration/__init__.py", line 191, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "[...]/south/migration/migrators.py", line 221, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "[...]/south/migration/migrators.py", line 292, in migrate_many
    result = self.migrate(migration, database)
  File "[...]/south/migration/migrators.py", line 125, in migrate
    result = self.run(migration)
  File "[...]/south/migration/migrators.py", line 99, in run
    return self.run_migration(migration)
  File "[...]/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "[...]/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "[...]/migrations/0001_initial.py", line 19, in forwards
    ('stack', self.gf('dbarray.TextArrayField')(default=[])),
  File "[...]/south/db/generic.py", line 226, in create_table
    ', '.join([col for col in columns if col]),
  File "[...]/south/db/generic.py", line 150, in execute
    cursor.execute(sql, params)
  File "[...]/django/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "[...]/django/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: missing dimension value
```

**Comment by mixmastamyk** [comment]
Was having the same problem.  Tried to do it by hand with the psql array default {} syntax and got the same error.  I decided to add null=True to the model instead and redo the migration.  That got me though it.

**Comment by rafales** [comment]
Turns out south generates wrong sql when there's default value set on field:

```
ALTER TABLE "my_table" ADD COLUMN "my_column" varchar(32)[] NOT NULL DEFAULT '[]';
```

while proper sql would look like this:

```
ALTER TABLE "my_table" ADD COLUMN "my_column" varchar(32)[] NOT NULL DEFAULT '{}'
```

Workaround for now: open your migration file and change default value  to '{}', like this:

```
db.add_column('my_table', 'my_column', self.gf('dbarray.CharArrayField')(max_length=32, default='{}'), keep_default=False)
```

**Comment by eykd** [comment]
Hm, my problems seem to go away when I don't specify a default. What's the appropriate way to specify a default value?

**Comment by ronnieoburke** [comment]
I followed @rafales advice and changed the default from [] to {} which fixed my migration.

**Comment by ses4j** [comment]
This problem still exists with Django 1.7 built-in migrations.
